include: package:flutter_lints/flutter.yaml

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    use_build_context_synchronously: false
    avoid_function_literals_in_foreach_calls: false